# Generated by Django 5.2.17 on 2026-10-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('origin_label', models.CharField(blank=True, default='', max_length=255)),
                ('destination_label', models.CharField(blank=True, default='', max_length=255)),
                ('distance_meters', models.FloatField()),
                ('duration_seconds', models.FloatField()),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('geometry', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.CharField(blank=True, default='', max_length=32)),
                ('price', models.FloatField(help_text='Retail price in USD per gallon')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ('price', 'name'),
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='routing_fue_latitud_6dc999_idx'), models.Index(fields=['city', 'state'], name='routing_fue_city_c91742_idx')],
            },
        ),
    ]
